<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RegistroVenta extends Model
{
    protected $table = 'registroventas';

    protected $primaryKey = 'DUAL';

    protected $fillable = [
        'DUAL', 'FECHAEMISION', 'FECHAVENCIMIENTO', 'TIPOCOMPROBANTE', 'SERIECO', 'NUMEROCO', 'TIPODOCUMENTO', 
        'NRODOCUMENTO', 'RAZONNOMBRE', 'DIRECCION', 'VEXPORTACION', 'IGVTASA', 'IGVIPM', 'ISC', 'OTROSTRIBUTOS', 
        'BASEIMPONIBLE', 'INAFECTAS', 'TOTALEXONERADA', 'GRATUITAS', 'TIPODSCTO', 'DSCTOUNIT', 'DSCTOGLOBAL', 
        'DESCUENTOS', 'TIPOCARGO', 'CARGOUNIT', 'CARGOGLOBAL', 'CARGOS', 'IMPORTETOTAL', 'MONEDA', 'TIPOCAMBIO', 
        'PERCEPUNIT', 'PERCEPCION', 'TIPOPAGO', 'RCPFECHA', 'RCPTIPO', 'RCPSERIE', 'RCPNUMERO', 'MOTIVONOTA', 
        'CODIGONOTA', 'TIPOGUIA', 'GUIAREMISION', 'PLACA', 'FECHATURNO', 'TURNO', 'HORA', 'PUNTOVENTA', 
        'MAQUINAVENTA', 'SITUACION', 'ENVIOSUNAT', 'FECHAENVIO', 'IDSESION', 'CAJERO', 'AFECTARSTOCK', 'NPFACTURADO', 
        'ENVIOCONTABILIDAD', 'USERID', 'GLOSA', 'TRANSPORTABLE', 'ENVIOWEB', 'RESOLUCION', 'ALMACEN', 'ENTREGA', 
        'COMPROBANTEELECTRONICO', 'ESPECIALIDAD', 'NROHISTORIA', 'MEDICO', 'PPCONVENIO', 'CONVENIO', 'REFERENCIA', 
        'DATAVALIDADA', 'ESTADOPLE', 'RESUMENID', 'NROSORTEO', 'TASAICBPER', 'CAT15_ELEM1', 'CAT15_ELEM2', 
        'CAT15_ELEM3', 'CAT15_ELEM4', 'CODDIRECCION', 'CODLOCALANEXO', 'PAGOEFECTIVO', 'TIPOCLIENTE', 'ORDENVENTA', 
        'ENVIOWEBSERVICE', 'TIPOOPERACION', 'TOTALANTICIPOS', 'IDCRM', 'NROCUOTAS', 'TELEFONO', 'GARANTIA', 
        'AUTORIZACION', 'FECHACREACION', 'TURNOCREACION', 'NROCANJE', 'NUMPAGO'
    ];

    protected $hidden = [
        'FECHAEMISION', 'FECHAVENCIMIENTO', 'TIPOCOMPROBANTE'
    ];
}
